Develop
KartmanJ/java-explore-with-me pull request #2
Opened 2023-01-03 13:10 UTC by KartmanJ

Разработаны main сервис и сервис статистики.

2023-01-09 17:44 UTC, damirovna requested changes
Сейчас я проверила:

1. Работа со сборкой
2. работа с докером
3. струтуры БД
4. модель данных
5. Объектов DTO

_Нужно исправить работу с просмотрами и внести правки в модель и объекты ДТО не только для события, но и аналогично для всех сущностей._

В следующей проверке я буду проверять контроллеры и сревисы, и исследовать ваш код на предмет запросов в базу или сервис статистики в цикле, такого быть не должно.

2023-01-09 17:44 UTC, damirovna commented on server/src/main/resources/schema.sql
> +    email VARCHAR(60)                             NOT NULL UNIQUE
60 - слишком маленькое ограничение на email.

2023-01-09 17:44 UTC, damirovna commented on server/src/main/resources/schema.sql
> +    confirmed_requests   BIGINT,
Это поле не должно быть в базе сервиса, так как его нужно вычислить в `EventService`

2023-01-09 17:44 UTC, damirovna commented on server/src/main/resources/schema.sql
> +    views                BIGINT DEFAULT 0
Это поле не должно быть в базе сервиса, так как его нужно вычислить в `EventService`

2023-01-09 17:44 UTC, damirovna commented on server/src/main/resources/schema.sql
> +    compilation_id BIGINT NOT NULL references compilations (id) on delete cascade
Нужно добавить  PRIMARY KEY, например: 
`CONSTRAINT pk_ event_compilations PRIMARY KEY (compilation_id, event_id)`

2023-01-09 17:44 UTC, damirovna commented on server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS event_locations
Такой вариант допустим, но мне кажется создание ещё одной таблицы всё-таки излишне, можно просто в таблице events ссылаться на locations

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/Event.java
> +    @OneToOne
В данном случае связь ManyToOne

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/Event.java
> +    @OneToOne
В данном случае связь ManyToOne

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/Event.java
> +    private Long views;
Данные views и confirmedRequests мы должны получать из сервиса статистики, а не хранить их в базе.

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventDto.java
> +    private Integer participantLimit;
Нужно добавить аннотацию @PositiveOrZero

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputShortDto.java
> +public class EventOutputShortDto {
Обратите внимание, что все поля этого класса дублируются в классе EventOutputDto используйте наследование, чтобы избежать дублирования кода

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputShortDto.java
> +
Нужно добавить аннотацию  @NotBlank полям:
- title
- annotation
Аннотацию @NotNull полям:
- category
- eventDate
- initiator
И аннотацию @PositiveOrZero к полям:
- views
- confirmedRequests

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputShortDto.java
> +    private String createdOn;
это поле не должно быть в схеме EventShortDto

2023-01-09 17:44 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputDto.java
> +public class EventOutputDto {
замечания аналогичные EventOutputShortDto

2023-01-09 18:03 UTC, KartmanJ commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputShortDto.java
> +
не согласен. класс используется исключительно на вывод информации, поэтому фактически в коде нигде эти проверки осуществляться не будут.

2023-01-09 18:15 UTC, KartmanJ commented on server/src/main/java/ru/practicum/explorewithme/model/event/Event.java
> +    @OneToOne
Судя по dto, подаваемому на вход - событие относится к одной конкретной категории, т.к. подаётся не список из id категорий, а конкретное значение.

2023-01-09 18:16 UTC, KartmanJ commented on server/src/main/java/ru/practicum/explorewithme/model/event/Event.java
> +    @OneToOne
поэтому связь один к одному.

2023-01-09 18:18 UTC, KartmanJ commented on server/src/main/java/ru/practicum/explorewithme/model/event/Event.java
> +    @OneToOne
и тут не соглашусь - один к одному, т.к. у эвента не может быть 2 инициатора.

2023-01-09 21:58 UTC, KartmanJ commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputShortDto.java
> +public class EventOutputShortDto {
Не вижу причин использовать наследование. При написании кода классы EventOutputDto и EventOutputShortDto используется как своего рода спецификации для работы с его полями. Очень часто 
 при написании кода приходится к этим классам обращаться. При использовании наследования вместо обращения к одному классу - придётся ещё обращаться и к классу-родителю, чтобы вспомнить, что там за поля ещё не обработаны. В принципе согласен, но можно и без наследования обойтись, если по ресурсам приложения просадки нет(чего я не знаю и с удовольствием почитал бы статейку на эту тему, если она у Вас имеется). Если есть - поправлю после второго ревью.

2023-01-10 15:33 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputShortDto.java
> +public class EventOutputShortDto {
Нет, это просто рекомендация, как сделать ваш код более качественным, эта правка не обязательная, просто рекомендация, так как дублирование кода не самое лучшее решение. Я предлагаю вам создать базовый класс и наследоваться от него, если вы найдёте такой вариант подходящим для вашей работы.

2023-01-10 15:35 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/dto/EventOutputShortDto.java
> +
Мы не можем предугдать, как будет развиваться проект и как будут использовать данный класс другие разработчики, нужно всегда стараться защищать себя от ошибок.

2023-01-10 15:37 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/model/event/Event.java
> +    @OneToOne
Вам нужно разобраться в данной теме, по вашим комментариям вижу, что с ней есть проблема

2023-01-10 15:39 UTC, damirovna requested changes
К сожалению, не все критичные замечания были исправлены, жду ваших доработок. Данную попытку засчитывать не буду, у вас остаётся две попытки сдать диплом.

2023-01-11 15:17 UTC, damirovna requested changes
В целом всё хорошо, но нужно избавиться от запросов в сервис статистики в цикле.

2023-01-11 15:17 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/component/EventBuildHelper.java
> +        return events.stream()
В данном случае будут производиться запросы в сервис статистики в цикле, такого быть не должно.

2023-01-11 15:17 UTC, damirovna commented on server/src/main/java/ru/practicum/explorewithme/component/EventBuildHelper.java
> +        return events.stream()
Аналогично. В данном случае будут производиться запросы в сервис статистики в цикле, такого быть не должно. Сделайте один запрос и после обработайте результат.

2023-01-13 14:48 UTC, damirovna approved these changes
поздравляю!

2023-04-29 19:39 UTC, merged